/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alexy' at '22/05/17 15:25' with Gradle 2.13
 *
 * @author Alexy, @date 22/05/17 15:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
